// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sampleget": {
            "get": {
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Commons.ResponseModel"
                        }
                    }
                }
            }
        },
        "/samplepost": {
            "post": {
                "parameters": [
                    {
                        "description": "Sample data",
                        "name": "requestBody",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Sample.SampleBusinessServiceInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/Commons.ResponseModel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "Commons.ResponseDetail": {
            "type": "object",
            "properties": {
                "Data": {},
                "ErrorMessages": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "IsSuccess": {
                    "type": "boolean"
                },
                "Message": {
                    "type": "string"
                },
                "ResultCode": {
                    "type": "integer"
                }
            }
        },
        "Commons.ResponseModel": {
            "type": "object",
            "properties": {
                "httpStatusCode": {
                    "type": "integer"
                },
                "responseDetil": {
                    "$ref": "#/definitions/Commons.ResponseDetail"
                }
            }
        },
        "Sample.SampleBusinessServiceInput": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
